### ISSUE TITLE
Clock CSS Issues

### ISSUE THREAD

**Issue by vishnuramana** [vishnuramana/analogclock#14]
### Issue 1: 
The clock hands and center size do not reduce relative to the size of the clock base size. This can be reproduced by setting size = 50px

#### Screenshot:

![image](https://user-images.githubusercontent.com/10045752/95741251-92658600-0cab-11eb-987d-f81cfe740cf5.png)

### Issue 2: 
The clock hands extend beyond the base when the clock size <200px. 

#### Screenshot:

![image](https://user-images.githubusercontent.com/10045752/95741185-73ff8a80-0cab-11eb-9e13-14f9a5bc5fca.png)

### Issue 3:
When the clock size is <100px, the base circle moves towards the right and is still not centered.

#### Screeshot:

![image](https://user-images.githubusercontent.com/10045752/95741242-90032c00-0cab-11eb-83d6-655319486279.png)

**Comment by ZsuzsaMano** [comment]
I like to play with css. Can I do it?

**Comment by vishnuramana** [comment]
Sure, please go ahead !

**Comment by ZsuzsaMano** [comment]
So I watched it very closely at 3 and at 9 o'clock, and it looks perfect
Maybe you can add hacktoberfest as a topic and get more people to check it. For me it looks just fine.

**Comment by vishnuramana** [comment]
Did you try reducing the clock size and see? I think the issue happens when the clock size is smaller than 200px.

**Comment by ZsuzsaMano** [comment]
I see. You should specify the problem a bit more in detail. Could you add a
screenshot?

Vishnu Ramana <notifications@github.com> ezt írta (időpont: 2020. okt. 12.,
Hét 6:41):

**Comment by vishnuramana** [comment]
I just updated the issues with screenshots. Let me know if you need anything else to work on this.

**Comment by ZsuzsaMano** [comment]
A new computer. This one keeps crashing every time I open a text-editor. :). Thx for the updates. I will check it as soon as I manage to unfreeze Atom. 
OK, now I understand the problem.

**Comment by ZsuzsaMano** [comment]
So at the moment actually it is not possible to reduce it under 200px. What should be the smallest value one can give?

**Comment by vishnuramana** [comment]
> So at the moment actually it is not possible to reduce it under 200px. What should be the smallest value one can give?

In the demo page, I have set the lower limit of the slider to 200px, but in use, you can actually set any size you want. (You can try that using React tools and setting the base size in the options object to view it.)

> I find the 100px is already quite small. I would put that as a limit. What do you think?

No, we do not want to set a limit to the size of the clock. 100px seems to be the best option for a clock but, some users might also go down to 50px, if they have a widget which also has an analog clock inside it. If we make the clock components relative to the base size of the clock, we do not have to worry about the rest.
