### ISSUE TITLE
CSS Issues

### ISSUE THREAD

**Issue by vishnuramana** [vishnuramana/analogclock#17]
### Issue 1: 
The clock hands and center size do not reduce relative to the size of the clock base size. This can be reproduced by setting size = 50px

The clock hands and center circle should have a min and max thickness/size beyond which it shouldn't grow or shrink ie. it shouldn't become so thin or too large when the base size is increased or decreased respectively.

Screenshot:

![image](https://user-images.githubusercontent.com/10045752/95741251-92658600-0cab-11eb-987d-f81cfe740cf5.png)

### Issue 2: 
The clock hands extend beyond the base when the clock size <200px. 

When the clock base size is reduced, the second hand's length is going beyond the border. It should always be touching the border circumference (when border=true) / should touch the circumference of the clock (when border = false).

#### Screenshot:

![image](https://user-images.githubusercontent.com/10045752/95741185-73ff8a80-0cab-11eb-9e13-14f9a5bc5fca.png)

### Issue 3:

When the clock size is <100px, the base circle moves towards the right and is still not centered.

#### Screeshot:

![image](https://user-images.githubusercontent.com/10045752/95741242-90032c00-0cab-11eb-83d6-655319486279.png)

**Comment by ethelius** [comment]
I've made a PR for issues 1 and 2! Issue 3 would require reworking of CSS in a way that the border of the clock can't just be 5% of total width anymore, it would have to be a constant pixel value (or a dynamically calculated pixel value that depends on the `width` prop being provided in px).

**Comment by vishnuramana** [comment]
Thanks for the PR. Closing this issue. I will raise a new Issue for Issue 3 listed above.
