### ISSUE TITLE
Literally Malware

### ISSUE THREAD

**Issue by GrantBaum** [vishnuramana/analogclock#20]
Dont download

**Comment by vishnuramana** [comment]
Can you please explain the issue ?

**Comment by GrantBaum** [comment]
tried to run it and it is literally "a known bad program"

**Comment by vishnuramana** [comment]
Can you be a little more specific about what you mean by "a known bad program" ? Are you talking about any dependabot alerts ?

**Comment by GrantBaum** [comment]
Windows virus protection said it was a bad program and wouldnt let it run.

**Comment by vishnuramana** [comment]
Can you provide a screenshot of the Windows error that you are seeing ? The code does not contain any malware. Moreover, if Windows virus protection says it's a bad program, it might be talking about your node installation (which you may have to bypass in Windows proxy.)

Until I can see some error messages or screenshots of what you are saying, I will not be able to help resolve the issue.

**Comment by GrantBaum** [comment]
it says "A KNOWN BAD PROGRAM TRYING TO RUN WAS STOPPED"

**Comment by vishnuramana** [comment]
Can you provide a screenshot of the error that you are seeing? I'm not aware of any windows application giving this error. 

Also please provide the below information:

1. How are you running the code? What command are you using ?
2. Which application is giving the error "A KNOWN BAD PROGRAM TRYING TO RUN WAS STOPPED" ? A screenshot of the application throwing the error is needed.
3. Which version of Node, React and styled-components are you using ?

**Comment by vishnuramana** [comment]
Closing this issue as I'm not able to find the "malware" reported by reporter.
