### ISSUE TITLE
LITERALLY MALWARE (TRIED TO DELETE IT)

### ISSUE THREAD

**Issue by GrantBaum** [vishnuramana/analogclock#23]

**Comment by vishnuramana** [comment]
@GrantBaum You did not provide any valid inputs to replicate the issue (refer #20) or provide a proper error message screenshot of the supposed "malware" that you are seeing. Unless you provide them, I will not be taking this as an issue as I'm very confident that the code has nothing to do with malware. 

I will wait for a day for you to provide the necessary proofs. If not, I will be closing this issue and any further attempts to create the issue for the same will be reported as SPAM.

**Comment by vishnuramana** [comment]
@GrantBaum What is the point of raising issues when you can't provide any proof about the error ? ALSO, **ANY ATTEMPT TO RAISE THIS ISSUE WITHOUT ANY PROOF WILL BE MARKED AS SPAM AND YOUR ACCOUNT WILL BE REPORTED.**
