### ISSUE TITLE
It has issues with production built gatsbyjs

### ISSUE THREAD

**Issue by cxspxr** [vishnuramana/analogclock#9]
Unfortunately I can't share the closed source code, but in case you are interested there is a problem with gatsbyjs integration.

The exact problem is that if you go to the built page with react-clock inside it - firstly it shows only the second hand, until there is a tick for minute happens - then it shows the minute hand. Until there is a tick for hour hand happens - then it shows all 3 of them.

https://imgur.com/a/9IypTB8

I am not sure exactly why

Steps to reproduce:

```
$ npm i -g gatsby-cli serve
$ gatsby new gatsby-site
$ cd gatsby-site
$ npm i analog-clock-react
... import analog-clock-react to src/pages/index.js and render with any config in order to make it appear on the root route ...
$ gatsby build
$ serve public
```

It is not always reproducible, but I want to share this problem with you anyway

**Comment by vishnuramana** [comment]
Thanks for raising this issue and sorry for the late reply. 

This seems weird. I think the render doesn't happen until a change happens so likely something to do with React. Let me take a look.
